name: Build XoDos Bootstrap

on:
  workflow_dispatch:

jobs:
  build-xodos-bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout XoDos Termux-Packages repo
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y wget tar zip build-essential

      - name: Set TERMUX_APP_PACKAGE for XoDos
        run: |
          echo 'TERMUX_APP_PACKAGE="com.xodos"' >> ./scripts/properties.sh
          echo 'TERMUX_PREFIX="/data/data/com.xodos/files/usr"' >> ./scripts/properties.sh

      - name: Run generate-bootstraps.sh
        run: |
          chmod +x ./scripts/generate-bootstraps.sh
          ./scripts/generate-bootstraps.sh --architectures aarch64 --android10

      - name: Upload bootstrap zip
        uses: actions/upload-artifact@v4
        with:
          name: xodos-bootstrap-aarch64
          path: bootstrap-aarch64.zip
