name: Build XoDos Bootstrap

on:
  workflow_dispatch:

jobs:
  build-xodos-bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout XoDos Termux-Packages repo
        uses: actions/checkout@v4

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          docker --version

      - name: Set custom XoDos package name
        run: |
          sed -i 's|TERMUX_APP_PACKAGE=.*|TERMUX_APP_PACKAGE="com.xodos"|' ./scripts/properties.sh
          sed -i 's|TERMUX_PREFIX=.*|TERMUX_PREFIX="/data/data/com.xodos/files/usr"|' ./scripts/properties.sh
          
      - name: Disable all SHA256 checksums safely
        run: |
          echo "$SKIP_CHECKSUM"
          #find . -type f -name "build.sh" -exec sed -i \
          #-E '/^TERMUX_PKG_SHA256=/s|=.*|="SKIP_CHECKSUM"|' {} +
         
          - name: Build bootstrap packages
            run: |
              ./scripts/run-docker.sh ./build-package.sh libandroid-support
              ./scripts/run-docker.sh ./build-package.sh termux-elf-cleaner
              ./scripts/run-docker.sh ./build-package.sh termux-exec
              ./scripts.run-docker.sh ./build-package.sh bash
              ./scripts/run-docker.sh ./build-package.sh bzip2
              ./scripts/run-docker.sh ./build-package.sh coreutils
              ./scripts/run-docker.sh ./build-package.sh curl
              ./scripts/run-docker.sh ./build-package.sh diffutils
              ./scripts/run-docker.sh ./build-package.sh findutils
              ./scripts/run-docker.sh ./build-package.sh gawk
              ./scripts/run-docker.sh ./build-package.sh grep
              ./scripts/run-docker.sh ./build-package.sh gzip
              ./scripts/run-docker.sh ./build-package.sh less
              ./scripts/run-docker.sh ./build-package.sh nano
              ./scripts/run-docker.sh ./build-package.sh ncurses
              ./scripts/run-docker.sh ./build-package.sh procps
              ./scripts/run-docker.sh ./build-package.sh sed
              ./scripts/run-docker.sh ./build-package.sh tar
              ./scripts/run-docker.sh ./build-package.sh unzip
              ./scripts/run-docker.sh ./build-package.sh util-linux
              ./scripts/run-docker.sh ./build-package.sh xz-utils
       
      - name: Run build-bootstraps.sh inside Docker
        run: |
          ./scripts/run-docker.sh ./scripts/build-bootstraps.sh --android10 --architectures aarch64

      - name: Upload XoDos bootstrap
        uses: actions/upload-artifact@v4
        with:
          name: xodos-bootstrap-aarch64
          path: bootstrap-aarch64.zip
