name: Build XoDos Bootstrap

on:
  workflow_dispatch:

jobs:
  build-xodos-bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout XoDos Termux-Packages repo
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y wget tar zip build-essential

      - name: Set XoDos package name and prefix
        run: |
          echo "TERMUX_APP_PACKAGE=com.xodos" >> $GITHUB_ENV
          echo "TERMUX_PREFIX=/data/data/com.xodos/files/usr" >> $GITHUB_ENV

      - name: Disable SHA256 checksum (force SKIP_CHECKSUM)
        run: |
          find . -type f -name "build.sh" -exec sed -i \
            -E 's/^(TERMUX_PKG_SHA256)=.*/\1="SKIP_CHECKSUM"/' {} +

      - name: Run generate-bootstraps.sh
        run: |
          chmod +x ./scripts/generate-bootstraps.sh
          ./scripts/generate-bootstraps.sh --architectures aarch64 --android10

      - name: Upload bootstrap zip
        uses: actions/upload-artifact@v4
        with:
          name: xodos-bootstrap-aarch64
          path: bootstrap-aarch64.zip
