name: Build XoDos Bootstrap

on:
  workflow_dispatch:

jobs:
  build-xodos-bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout XoDos Termux-Packages repo
        uses: actions/checkout@v4

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          docker --version

      - name: Set custom XoDos package name
        run: |
          sed -i 's|TERMUX_APP_PACKAGE=.*|TERMUX_APP_PACKAGE="com.xodos"|' ./scripts/properties.sh
          sed -i 's|TERMUX_PREFIX=.*|TERMUX_PREFIX="/data/data/com.xodos/files/usr"|' ./scripts/properties.sh
          
      - name: Disable SHA256 checksum (force SKIP_CHECKSUM)
        run: |
          find . -type f -name "build.sh" -exec sed -i \
            -E 's/^(TERMUX_PKG_SHA256)=.*/\1="SKIP_CHECKSUM"/' {} +

       
      - name: Run build-bootstraps.sh inside Docker
        run: |
          ./scripts/run-docker.sh ./scripts/build-bootstraps.sh --android10 --architectures aarch64

      - name: Upload XoDos bootstrap
        uses: actions/upload-artifact@v4
        with:
          name: xodos-bootstrap-aarch64
          path: bootstrap-aarch64.zip
